import pathlib

from fastapi.templating import Jinja2Templates

BASE_DIR = pathlib.Path(__file__).resolve().parent
COARSE_GRAIN_MODELS_DIR = BASE_DIR / "coarse_grain" / "models"
TEMPLATES_DIR = BASE_DIR / "templates"
STATIC_DIR = BASE_DIR / "static"
WORKSPACE_STORAGE_DIR = BASE_DIR.parent / "temp"
TEMPLATES = Jinja2Templates(directory=TEMPLATES_DIR)

MODELS_IMAGES_DIR = STATIC_DIR / "images"
PRESETS_DIR = STATIC_DIR / "presets"
CITATIONS_DIR = BASE_DIR / "coarse_grain" / "metadata" / "citations.json"


BYTES_PER_KIB = 1024
BYTES_PER_MIB = 1024**2
BYTES_PER_GIB = 1024**3

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE

WORKSPACE_STORAGE_DIR.mkdir(parents=True, exist_ok=True)
RCSB_URL = "https://files.rcsb.org/download/"
MAX_FILE_UPLOAD_SIZE = 100 * BYTES_PER_MIB
MAX_RCSB_DOWNLOAD_SIZE = 100 * BYTES_PER_MIB

WORKSPACE_MAX_LIFETIME = 24 * SECONDS_PER_HOUR
WORKSPACE_CLEANUP_INTERVAL = 15 * SECONDS_PER_MINUTE
WORKSPACE_STORAGE_MAX_SIZE = 4 * BYTES_PER_GIB
MIN_FREE_DISK_SIZE = 2 * BYTES_PER_GIB

ALLOWED_PRESET_IDS = {"1EHZ", "1MNX", "2F8S"}
JSON_MAX_CHARS = 5000
JSON_MAX_UPLOAD_SIZE = 8 * BYTES_PER_KIB
