name: Build and Test
on: [push]
jobs:
  setup:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install pipenv
          pipenv install --dev
      - name: Save pipenv env
        uses: actions/upload-artifact@v4
        with:
          name: pipenv-env
          path: ~/.local/share/virtualenvs/
      - run: pipenv run ruff check .
      - run: pipenv run mypy .
      - run: pipenv run pytest ./tests/unit
      - uses: actions/download-artifact@v4
        with:
          name: pipenv-env
          path: ~/.local/share/virtualenvs/
      - run: pip install pipenv
      - run: pipenv run pytest ./tests/e2e
