name: Build and Test
on: [push, pull_request]
jobs:
  setup:
    name: Setup & Build Tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci
      - run: npm run dev
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/virtualenvs
            ~/.cache/pip
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - run: |
          pip install pipenv
          pipenv install --dev
      - name: Upload CSS
        uses: actions/upload-artifact@v4
        with:
          name: built-css
          path: |
            app/static/css/
            app/styles/
      - name: Save pipenv env
        uses: actions/upload-artifact@v4
        with:
          name: pipenv-env
          path: ~/.local/share/virtualenvs/
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pipenv -d
      - run: pipenv run ruff check .

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pipenv -d
      - run: pipenv run mypy .

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pipenv -d
      - run: pipenv run pytest ./tests/unit

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/download-artifact@v4
        with:
          name: pipenv-env
          path: ~/.local/share/virtualenvs/
      - run: pip install pipenv -d
      - run: pipenv run pytest ./tests/e2e
