name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --dev
      - name: ruff
        run: pipenv run ruff check .
      - name: mypy
        run: pipenv run mypy .
      - name: unit
        run: pipenv run pytest ./tests/unit/.
      - name: e2e
        run: pipenv run pytest ./tests/e2e/.
        
