name: Build Tailwind CSS
on:
  push:
    paths:
      - 'app/templates/**'
      - 'tailwind.config.js'
      - 'package.json'
      - 'app/static/css/input.css'
      - '.github/workflows/tailwind-build.yaml'
  pull_request:
    paths:
      - 'app/templates/**'
      - 'tailwind.config.js'
      - 'package.json'
      - 'app/static/css/input.css'

jobs:
  build-tailwind:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip css]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Install Node dependencies
        run: npm install
      - name: Build Tailwind CSS
        run: npm run dev
      - name: Commit CSS changes
        if: steps.css-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/static/css/ app/styles/
          git commit -m "🎨 Auto-build Tailwind CSS [skip css]" || exit 0
      - name: Push changes
        if: steps.css-changes.outputs.changes == 'true'
        run: |
          git push